#!/usr/local/bin/bash
DEBUG "zsh overrides" "Executing (Inside File)";
# -= PROMPT: PRECMD HOOK OVERRIDE =-
function precmd() {
    local _exitValue=$?;
    local _prefix="/Users/stephen-harold/.local/profiles/zsh.d";
    local _filePS1="${_prefix}/zshPS01";
    local _filePS2="${_prefix}/zshPS02";
    [[ -r "${_filePS1}" ]] && PS1=$( "${_filePS1}" "${_exitValue}" || PS1="[%n@%M] (%2~)\#\#: ")
    [[ -r "${_filePS2}" ]] && PS2=$( "${_filePS2}" "${_exitValue}" || PS2="(%2~)$: ")
}


