#!/bin/bash
returnValue=$1;

function textErrorFunction() {
	echo "%{${whiteOnRed}%}${UL}Error ${LU}%{${RESET}%}%{${redOnWhite}%}${UL} $1 %{$LU$RESET%}";
}

function returnPrompt()	{
	echo $( [[ "$returnValue" != 0 ]] && echo textErrorFunction $returnValue || echo $textPath ) $textShellPink"\:> ";
}

returnPrompt;
