#!/bin/bash
returnValue=$1;

function textErrorFunction() {
	echo "%{${whiteOnRed}%}${UL}Error ${LU}%{${RESET}%}%{${redOnWhite}%}${UL} ${returnValue} %{${LU}${RESET}%} ${_textShellPink}\:> ";
}

function echoPrompt()	{
	local _textPath;
	_textPath=$([[ "${PWD}" = "/Users/stephen-harold" ]] && echo "%{${WHITE}%}('${home}%{${WHITE}%}')%{${RESET}%}" || echo "%{${WHITE}%}(%2~%{${CYAN}%}/%{${WHITE}%})%{${RESET}%}");
	local _textShellPink="%{${PINK}%}${SHELL//*\/}%{${RESET}%}";
	[[ "${returnValue}" != 0 ]] && echo textErrorFunction "${returnValue}" || echo "${_textPath} ${_textShellPink}\:> ";
}

echo echoPrompt;
unset returnValue;
