#!/usr/local/bin/bash
# shellcheck disable=SC2155

[[ $(type DEBUG) =~ 'function' ]] && DEBUG "bash overrides" "Executing";

function setPrompt() {
    local _returnValue=$1;
    [[ -z ${dBASH} ]] && export PS1="[\u@\h](\w)$: "; export PS2="(\w)$: "
    local _ps1File="${dBASH}/bashPS01";
    local _ps2File="${dBASH}/bashPS02";
    [[ -r ${_ps1File} ]] && export PS1=$( ${_ps1File} "${_retrunValue}" )
    [[ -r ${_ps2File} ]] && export PS1=$( ${_ps2File} "${_retrunValue}" )
    [[ -z ${PS1} ]] && export PS1="[\u@\h](\w)$: "; export PS2="(\w)$: "
}

PROMPT_COMMAND=setPrompt "$?";
