#!/usr/local/bin/bash
clear

# -= FILES: SOURCE PROFILE FILES =-
function sourceProfile() {
	declare -a arrayBashSourcedFiles;
	arrayBashSourcedFiles=( \
			"/Users/stephen-harold/.local/profiles/common.d/commonConfig" \
			"/Users/stephen-harold/.local/profiles/common.d/commonExports" \
			"$dirCOMMON/commonAilieses" \
			"$dirCOMMON/commonOverrides" \
			"$dirCOMMON/commonPeriodics" \
			"$dirBASH/bashExports" \
			"$dirBASH/bashAiliases" \
			"$dirBASH/bashOverrides" );

	for number in {0..7}
	do
		local thisFile=${arrayBashSourcedFiles[$number]};
		[[ -r $thisFile ]] && source $thisFile || echo -e "$number. \e[0;31mFile \e[0;4;31mnot\e[m \e[0;31mfound:\e[1;37m $thisFile \e[m"
		# ß$( DEBUG "bashProfile" "$index. Called source on $thisFile." );
	done
	#$( DEBUG "bashProfile" "Called source on all "${#arrayBashSourcedFiles[*]}" files in total." );
}

sourceProfile;
unset -f sourceProfile;
#$( DEBUG "bashProfile" "Complete" );
