#!/bin/bash
returnValue=$1;

function textErrorFunction() {
	echo "%{${whiteOnRed}%}${UL}Error ${LU}%{${RESET}%}%{${redOnWhite}%}${UL} $1 %{$LU$RESET%}";
}

function returnPrompt()	{
	# prompt preconfigured text snippets
	local home=$( tput setaf $(( $RANDOM % 254 + 1 )); printf "H"; \
								 tput setaf $(( $RANDOM % 50 + 1 )); printf "o"; \
								 tput setaf $(( $RANDOM % 50 + 1 )); printf "m"; \
								 tput setaf $(( $RANDOM % 254 + 1 )); printf "e"; \
								 tput sgr0; );
	local textRoot="${hostDecor}${UL}|$hostROOT$hostDecor|${LU}$RESET";
	local textHost="${hostDecor}${UL}${hostClr}${HOSTNAME//\.*}${hostDecor}${LU}${RESET}";
	local textPath=$([[ "$PWD" = "/Users/stephen-harold" ]] && \
			echo "${WHITE}('${home}${WHITE}')${RESET}" || \
			echo "${WHITE}(%2~${CYAN}/${WHITE})${RESET}");
	local textShell=$( echo "${GREEN}${SHELL//*\/}${RESET}" );
	local textShellPink=$( echo "%{$PINK%}${SHELL//*\/}%{$RESET%}" );
	local textTime="${BlueOnBlue}${UL}|$(date +%H:%M)|${LU}${RESET}";
	echo $( [[ "$returnValue" != 0 ]] && textErrorFunction $returnValue || echo $textHost ) $textPath $textShell": ";
}

returnPrompt;
