#!/usr/local//bin/bash
filename=$0;
[[ $(type DEBUG) =~ 'function' ]] && DEBUG "${filename}" "executing (DEBUG is defined)" # This will never be seen!
# terminal foreground text colours
declare -gx RED;
RED=$( tput setaf 160);
declare -gx GREEN;
GREEN=$(tput setaf 40);
declare -gx BLUE;
BLUE=$(tput setaf 33);
declare -gx WHITE;
WHITE=$(tput setaf 15);
declare -gx YELLOW;
YELLOW=$(tput setaf 220);
declare -gx CYAN;
CYAN=$(tput setaf 51);
declare -gx BLACK;
BLACK=$(tput setaf 232);
declare -gx PURPLE;
PURPLE=$(tput setaf 56);
declare -gx PINK;
PINK=$(tput setaf 201);
declare -gx TEAL;
TEAL=$(tput setaf 41);
# terminal text decorations
declare -gx BOLD;
BOLD=$(tput bold);
declare -gx UL;
UL=$(tput smul);
declare -gx LU;
LU=$(tput rmul);
# terminal text colours, foreground & background
declare -gx redOnWhite;
redOnWhite=$(tput setab 15; tput setaf 1;);
declare -gx whiteOnRed;
whiteOnRed=$(tput setab 1; tput setaf 15;);
declare -gx BlueOnBlue;
BlueOnBlue=$(tput setab 17; tput setaf 12;);
declare -gx RESET;
RESET=$(tput sgr0);


# -= ENV: EXPORTS =-
export PAGER=less;
export EDITOR=nano;
export GREP_COLOR=36;
export USERNAME=${LOGNAME};
export HOSTNAME=${HOST};
export dCOMMON="/Users/stephen-harold/.local/profiles/common.d";
export dZSH="/Users/stephen-harold/.local/profiles/zsh.d";
export dBASH="/Users/stephen-harold/.local/profiles/bash.d";
export dPROFILES_DEBUG="Off";
export dUTILS="/usr/local/lib/utils.d";
export dUTILS_DEBUG="Off";
# DON'T MOVE OR EDIT THESE NEXT 2 LINES OF CODE!
# _tn=$( ps -afx | grep -i -E  '\-zsh' | grep -v 'grep' | wc -l );
# export TerminalTabsCount=$( echo $_tn | tr -d '[:space:]' );

# declaration debug function and export
declare -f -x DEBUG;
function DEBUG() {
        local scriptName=$1;
        local message=$2;
        [[ "${dPROFILES_DEBUG}" = 1 ]] && \
                  printf "${WHITE}DEBUG| %-16s ${WHITE}|| %-32s ${WHITE}||| %-120s ${WHITE}||||${RESET}\n" \
                          "${RED}$(date +%H:%M:%S)" \
                          "${YELLOW}${scriptName:-"Not Set!"}" \
                          "${GREEN}${message:-"Message Variable Not Set"}";
}
#    export -f DEBUG;
