#!/usr/local//bin/bash
filename=$0;
[[ $(type DEBUG) =~ 'function' ]] && DEBUG "${filename}" "executing (DEBUG is defined)" # This will never be seen!
# terminal foreground text colours
export RED=$( tput setaf 160);
export GREEN=$(tput setaf 40);
export BLUE=$(tput setaf 33);
export WHITE=$(tput setaf 15);
export YELLOW=$(tput setaf 220);
export CYAN=$(tput setaf 51);
export BLACK=$(tput setaf 232);
export PURPLE=$(tput setaf 56);
export PINK=$(tput setaf 201);
export TEAL=$(tput setaf 41);
# terminal text decorations
export BOLD=$(tput bold);
export UL=$(tput smul);
export LU=$(tput rmul);
export RESET=$(tput sgr0);
# terminal text colours, foreground & background
export redOnWhite=$(tput setab 15; tput setaf 1;);
export whiteOnRed=$(tput setab 1; tput setaf 15;);
export BlueOnBlue=$(tput setab 17; tput setaf 12;);


# -= ENV: EXPORTS =-
export PAGER=less;
export EDITOR=nano;
export GREP_COLOR=36;
export USERNAME=${LOGNAME};
export HOSTNAME=${HOST};
export du="/usr/local/lib/utils.d";
export dirCOMMON="/Users/stephen-harold/.local/profiles/common.d";
export dirZSH="/Users/stephen-harold/.local/profiles/zsh.d";
export dirBASH="/Users/stephen-harold/.local/profiles/bash.d";
export utilsDebug="Off";
# DON'T MOVE OR EDIT THESE NEXT 2 LINES OF CODE!
# _tn=$( ps -afx | grep -i -E  '\-zsh' | grep -v 'grep' | wc -l );
# export TerminalTabsCount=$( echo $_tn | tr -d '[:space:]' );

# declaration debug function and export
declare -f -x DEBUG;
function DEBUG() {
      local scriptName=$1;
      local message=$2;
      [[ "${DEBUG_ENABLED}" = 1 ]] && \
            printf "${WHITE}DEBUG| %-16s ${WHITE}|| %-32s ${WHITE}||| %-120s ${WHITE}||||${RESET}\n" \
                  "${RED}$(date +%H:%M:%S)" \
                  "${YELLOW}${scriptName:-"Not Set!"}" \
                  "${GREEN}${message:-"Message Variable Not Set"}";
}
#ß    export -f DEBUG;
