#!/bin/zsh

function periodic() {
    if [ $_tn -gt 1 ]
    then
        print -Pn "\e]2;$(uptime);\a" # Terminal Title
        print -Pn "\e]1; %m: %n  (  ${PWD/$HOME/'Home'}  ) \a" # Tab Title, when there's 2 or more tabs
    else
        print -Pn "\e]2;$(uptime);\a" # Terminal Title
    fi
}
export PERIOD=1
