#!/usr/local/bin/bash

# ENABLED
enable=require-variable-braces

# DISABLED
# SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.
disable=SC1090
# SC2154 (warning): <variable> is referenced but not assigned
disable=SC2154
# SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
disable=SC2317


